apiVersion: v1
kind: Secret
metadata:
  name: skillcareer-secrets
  namespace: dev
type: Opaque
stringData:
  MONGO_ROOT_USERNAME: admin
  MONGO_ROOT_PASSWORD: admin123
  JWT_SECRET: your-jwt-secret
  USER_SERVICE_MONGO_URI: mongodb://admin:admin123@mongodb.dev.svc.cluster.local:27017/skillcareer-user?authSource=admin
  CAREER_SERVICE_MONGO_URI: mongodb://admin:admin123@mongodb.dev.svc.cluster.local:27017/skillcareer-career?authSource=admin
  SKILL_SERVICE_MONGO_URI: mongodb://admin:admin123@mongodb.dev.svc.cluster.local:27017/skillcareer-skill?authSource=admin
  ROADMAP_SERVICE_MONGO_URI: mongodb://admin:admin123@mongodb.dev.svc.cluster.local:27017/skillcareer-roadmap?authSource=admin
  CONTENT_SERVICE_MONGO_URI: mongodb://admin:admin123@mongodb.dev.svc.cluster.local:27017/skillcareer-content?authSource=admin
  PROGRESS_SERVICE_MONGO_URI: mongodb://admin:admin123@mongodb.dev.svc.cluster.local:27017/skillcareer-progress?authSource=admin
