apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: skillcareer-secrets
  namespace: prod
spec:
  encryptedData:
    MONGO_ROOT_USERNAME: REPLACE_WITH_KUBESEAL_OUTPUT
    MONGO_ROOT_PASSWORD: REPLACE_WITH_KUBESEAL_OUTPUT
    JWT_SECRET: REPLACE_WITH_KUBESEAL_OUTPUT
    USER_SERVICE_MONGO_URI: REPLACE_WITH_KUBESEAL_OUTPUT
    CAREER_SERVICE_MONGO_URI: REPLACE_WITH_KUBESEAL_OUTPUT
    SKILL_SERVICE_MONGO_URI: REPLACE_WITH_KUBESEAL_OUTPUT
    ROADMAP_SERVICE_MONGO_URI: REPLACE_WITH_KUBESEAL_OUTPUT
    CONTENT_SERVICE_MONGO_URI: REPLACE_WITH_KUBESEAL_OUTPUT
    PROGRESS_SERVICE_MONGO_URI: REPLACE_WITH_KUBESEAL_OUTPUT
  template:
    metadata:
      name: skillcareer-secrets
      namespace: prod
    type: Opaque
