apiVersion: v1
kind: Secret
metadata:
  name: skillcareer-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  MONGO_ROOT_USERNAME: {{ .Values.secrets.mongoRootUsername | quote }}
  MONGO_ROOT_PASSWORD: {{ .Values.secrets.mongoRootPassword | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  USER_SERVICE_MONGO_URI: {{ .Values.secrets.userMongoUri | quote }}
  CAREER_SERVICE_MONGO_URI: {{ .Values.secrets.careerMongoUri | quote }}
  SKILL_SERVICE_MONGO_URI: {{ .Values.secrets.skillMongoUri | quote }}
  ROADMAP_SERVICE_MONGO_URI: {{ .Values.secrets.roadmapMongoUri | quote }}
  CONTENT_SERVICE_MONGO_URI: {{ .Values.secrets.contentMongoUri | quote }}
  PROGRESS_SERVICE_MONGO_URI: {{ .Values.secrets.progressMongoUri | quote }}
