name: progress-service-ci
on:
  workflow_dispatch:
  push:
    paths:
      - ''services/progress-service/**''
      - ''cicd/workflows/progress-service-ci.yml''
jobs:
  run:
    uses: ./cicd/workflows/reusable-service-ci.yml
    with:
      service_name: progress-service
      context_path: services/progress-service
      image_name: suwetha07/skillcareer-progress-service
