apiVersion: v1
kind: ConfigMap
metadata:
  name: skillcareer-config
  namespace: dev
data:
  USER_SERVICE_URL: http://user-service:5001
  CAREER_SERVICE_URL: http://career-service:5002
  SKILL_SERVICE_URL: http://skill-service:5003
  ROADMAP_SERVICE_URL: http://roadmap-service:5004
  CONTENT_SERVICE_URL: http://content-service:5005
  PROGRESS_SERVICE_URL: http://progress-service:5006
  VITE_API_BASE_URL: /api
  USE_IN_MEMORY_FALLBACK: "false"
---
apiVersion: v1
kind: Secret
metadata:
  name: skillcareer-secrets
  namespace: dev
type: Opaque
stringData:
  MONGO_ROOT_USERNAME: "admin"
  MONGO_ROOT_PASSWORD: "admin123"
  JWT_SECRET: "shared-secret"
  USER_SERVICE_MONGO_URI: "mongodb://admin:admin123@mongodb.dev.svc.cluster.local:27017/skillcareer?authSource=admin"
  CAREER_SERVICE_MONGO_URI: "mongodb://admin:admin123@mongodb.dev.svc.cluster.local:27017/skillcareer?authSource=admin"
  SKILL_SERVICE_MONGO_URI: "mongodb://admin:admin123@mongodb.dev.svc.cluster.local:27017/skillcareer?authSource=admin"
  ROADMAP_SERVICE_MONGO_URI: "mongodb://admin:admin123@mongodb.dev.svc.cluster.local:27017/skillcareer?authSource=admin"
  CONTENT_SERVICE_MONGO_URI: "mongodb://admin:admin123@mongodb.dev.svc.cluster.local:27017/skillcareer?authSource=admin"
  PROGRESS_SERVICE_MONGO_URI: "mongodb://admin:admin123@mongodb.dev.svc.cluster.local:27017/skillcareer?authSource=admin"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: skillcareer-config
  namespace: prod
data:
  USER_SERVICE_URL: http://user-service:5001
  CAREER_SERVICE_URL: http://career-service:5002
  SKILL_SERVICE_URL: http://skill-service:5003
  ROADMAP_SERVICE_URL: http://roadmap-service:5004
  CONTENT_SERVICE_URL: http://content-service:5005
  PROGRESS_SERVICE_URL: http://progress-service:5006
  VITE_API_BASE_URL: /api
  USE_IN_MEMORY_FALLBACK: "false"
---
apiVersion: v1
kind: Secret
metadata:
  name: skillcareer-secrets
  namespace: prod
type: Opaque
stringData:
  MONGO_ROOT_USERNAME: "admin"
  MONGO_ROOT_PASSWORD: "admin123"
  JWT_SECRET: "shared-secret"
  USER_SERVICE_MONGO_URI: "mongodb://admin:admin123@mongodb.prod.svc.cluster.local:27017/skillcareer?authSource=admin"
  CAREER_SERVICE_MONGO_URI: "mongodb://admin:admin123@mongodb.prod.svc.cluster.local:27017/skillcareer?authSource=admin"
  SKILL_SERVICE_MONGO_URI: "mongodb://admin:admin123@mongodb.prod.svc.cluster.local:27017/skillcareer?authSource=admin"
  ROADMAP_SERVICE_MONGO_URI: "mongodb://admin:admin123@mongodb.prod.svc.cluster.local:27017/skillcareer?authSource=admin"
  CONTENT_SERVICE_MONGO_URI: "mongodb://admin:admin123@mongodb.prod.svc.cluster.local:27017/skillcareer?authSource=admin"
  PROGRESS_SERVICE_MONGO_URI: "mongodb://admin:admin123@mongodb.prod.svc.cluster.local:27017/skillcareer?authSource=admin"
