apiVersion: v1
kind: ConfigMap
metadata:
  name: skillcareer-config
  namespace: dev
data:
  USER_SERVICE_URL: http://user-service:5001
  CAREER_SERVICE_URL: http://career-service:5002
  SKILL_SERVICE_URL: http://skill-service:5003
  ROADMAP_SERVICE_URL: http://roadmap-service:5004
  CONTENT_SERVICE_URL: http://content-service:5005
  PROGRESS_SERVICE_URL: http://progress-service:5006
  VITE_API_BASE_URL: /api
  USE_IN_MEMORY_FALLBACK: "false"
