name: skillcareer-progress-service
namespace: dev
image:
  repository: your-dockerhub/skillcareer-progress-service
  tag: latest
service:
  port: 5006
config:
  SAMPLE_KEY: sample
secrets:
  SAMPLE_SECRET: change-me
