apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skillcareer-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/suwetha07/skillcareer
    targetRevision: develop
    path: skillcareer-infra/k8s/dev  

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true