{{- if and .Values.secrets .Values.secrets.create }}
{{- $secretName := .Values.secrets.name | default "skillcareer-secret" -}}
{{- $secretData := .Values.secrets.data | default dict -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
type: Opaque
data:
{{- range $key, $value := $secretData }}
  {{ $key }}: {{ $value | toString | b64enc }}
{{- end }}
{{- end }}
