name: skillcareer-skill-service
namespace: dev
image:
  repository: your-dockerhub/skillcareer-skill-service
  tag: latest
service:
  port: 5003
config:
  SAMPLE_KEY: sample
secrets:
  SAMPLE_SECRET: change-me
