apiVersion: v1
kind: Secret
metadata:
  name: skillcareer-secret
  namespace: prod
type: Opaque
stringData:
  JWT_SECRET: shared-secret
  MONGO_URI: mongodb://mongodb:27017/skillcareer
  MONGO_ROOT_USERNAME: admin
  MONGO_ROOT_PASSWORD: admin123
