name: skillcareer-user-service
namespace: prod
image:
  repository: your-dockerhub/skillcareer-user-service
  tag: 1.0.0
service:
  port: 5001
config:
  SAMPLE_KEY: sample
secrets:
  SAMPLE_SECRET: change-me
