name: api-gateway-ci
on:
  workflow_dispatch:
  push:
    paths:
      - ''api-gateway/**''
      - ''.github/workflows/api-gateway-ci.yml''
jobs:
  run:
    uses: ./.github/workflows/reusable-service-ci.yml
    with:
      service_name: api-gateway
      context_path: api-gateway
      image_name: suwetha07/skillcareer-api-gateway
