name: frontend-ci
on:
  workflow_dispatch:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'
jobs:
  run:
    uses: ./.github/workflows/reusable-service-ci.yml
    with:
      service_name: frontend
      context_path: frontend
      image_name: suwetha07/skillcareer-frontend
